

#####################################################################################################

# GET https://localhost:5001/weatherforecasts HTTP/1.1

# Get all categories
GET https://localhost:5001/categorys HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYTc3Y2MwNS1iMWYxLTQ4MWYtYTRjNi02OWNlYzFiYzBiODkiLCJpYXQiOiIyMS8wMy8yMDIzIDE4LjUxLjE3IiwiZW1haWwiOiJzbWl0aGFrYW1hdGhAbWFpbC5jb20iLCJuYW1lIjoiU21pdGhhIiwiZXhwIjoxNjc5NDIxMDc3LCJpc3MiOiJTbWl0aGEiLCJhdWQiOiJBZG1pbiJ9.nwtpS83CPbS-6trI6usekXp9PJp5tk6x322eotaOtlo

# # Get a single category
GET https://localhost:5001/categorys/2 HTTP/1.1

# create a category
POST https://localhost:5001/categorys HTTP/1.1
content-type: application/json

{
    "Name": "New Category Created",
    "Image": "https://source.unsplash.com/164_6wVEHfI"
}

# Create a category
# POST https://localhost:5001/categorys HTTP/1.1
# content-type: application/json

# {
#     "Name": "New Category",
#     "ImageId": 1
# }

# Update a category
# PUT https://localhost:5001/categorys/2 HTTP/1.1
# content-type: application/json

# {
#     "Name": "New Category Updated second time",
#     "Image": "https://source.unsplash.com/164_6wVEHfI"
# }

# Delete a category
# DELETE https://localhost:5001/categorys/1 HTTP/1.1

# Get all products by category
# GET https://localhost:5001/categorys/3/products HTTP/1.1

#######################################################################################################

# Get all products
GET https://localhost:5001/products HTTP/1.1

GET https://localhost:5001/products HTTP/1.1
content-type: application/json

{
   "Sort": "Asc",
    "CardsPerPage":0,
    "Page":0
}

# Get a Single Product
# GET https://localhost:5001/products/1 HTTP/1.1 

#Authorizarion
GET https://localhost:5001/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYTc3Y2MwNS1iMWYxLTQ4MWYtYTRjNi02OWNlYzFiYzBiODkiLCJpYXQiOiIyMS8wMy8yMDIzIDE2LjA4LjQyIiwiZW1haWwiOiJzbWl0aGFrYW1hdGhAbWFpbC5jb20iLCJuYW1lIjoiU21pdGhhIiwiZXhwIjoxNjc5NDExMzIyLCJpc3MiOiJTbWl0aGEiLCJhdWQiOiJBZG1pbiJ9.uyMX31PMQZyUkQtXVvAGJgwzvY1xSJY8WPNftl6PtJI

###
GET https://localhost:5001/categorys/1/products HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYTc3Y2MwNS1iMWYxLTQ4MWYtYTRjNi02OWNlYzFiYzBiODkiLCJpYXQiOiIyMS8wMy8yMDIzIDE2LjQ4LjI4IiwiYXVkIjpbIkFkbWluIiwiQWRtaW4iXSwiZW1haWwiOiJzbWl0aGFrYW1hdGhAbWFpbC5jb20iLCJuYW1lIjoiU21pdGhhIiwiZXhwIjoxNjc5NDEzNzA4LCJpc3MiOiJTbWl0aGEifQ.Xoxu2DblIneLOnUZt46nEe9b1lNe-7mF2_co_Czl3UU
# Create a product
POST https://localhost:5001/products HTTP/1.1
content-type: application/json

{
    "Title": "New Category Products",
    "Price": 200,
    "Description": "New product",
    "CategoryID":2
}

# Update a product
PUT https://localhost:5001/products/1 HTTP/1.1
content-type: application/json

{
    "Title": "New Product1123",
    "Price": 500,
    "Description": "New product",
    "CategoryID":2
}

# Delete a product
# DELETE https://localhost:5001/products/3 HTTP/1.1

###############################################################################################

#Get All Users
# POST https://localhost:5001/users 

#Get By Guid
# GET https://localhost:5001/users/d06c52e3-41c0-4aab-9d9e-17ed500a0d7e

# #Create a new User
# POST https://localhost:5001/users/signup HTTP/1.1
# content-type: application/json

# {
#     "FirstName": "Nihan",
#     "LastName": "Anwer",
#     "UserName": "nihananwer",
#     "Email": "nihan@mail.com",
#     "Password": "Nihan@123",
#     "ConfirmPassword":"Nihan@123"
# }

# Create a new User
POST https://localhost:5001/signup HTTP/1.1
content-type: application/json

{
    "FirstName": "Smitha",
    "LastName": "Kamath",
    "UserName": "smithakamath",
    "Email": "smithawinner123@mail.com",
    "Password": "Smitha@123",
    "ConfirmPassword":"Smitha@123"
}

# Login and Get teh Access Token
###
POST https://localhost:5001/signin HTTP/1.1
content-type: application/json

{
    "Email": "smithaWinner@mail.com",
    "Password": "Smitha@123"
}

###############################################################################################################

# Add To Cart
###
POST https://localhost:5001/carts HTTP/1.1
content-type: application/json

{
    "UserId": "1a77cc05-b1f1-481f-a4c6-69cec1bc0b89",
    "ProductId": 2,
    "Quantity":10
}

# POST https://localhost:5001/carts HTTP/1.1
# content-type: application/json

# {
#     "UserId": "d06c52e3-41c0-4aab-9d9e-17ed500a0d7e",
#     "ProductId": 1,
#     "Quantity":10
# }


# POST https://localhost:5001/carts HTTP/1.1
# content-type: application/json

# {
#     "UserId":"d06c52e3-41c0-4aab-9d9e-17ed500a0d7e"
# }

//Get all the cart items belonginng to a user
# GET https://localhost:5001/carts/d06c52e3-41c0-4aab-9d9e-17ed500a0d7e HTTP/1.1

###
# GET https://localhost:5001/carts HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjIzMTA5ZC0zNmU2LTQ3N2MtOTQyMC0zNjdkNjZkYzBiNDYiLCJpYXQiOiIyMC8wMy8yMDIzIDExLjM3LjAzIiwiZW1haWwiOiJzbWl0aGFrYW1hdGhAbWFpbC5jb20iLCJuYW1lIjoiU21pdGhhIiwiZXhwIjoxNjc5MzA4NjIzLCJpc3MiOiJTbWl0aGEiLCJhdWQiOiJBZG1pbiJ9.dp48xGKvyAX5aBNvYbHAjQfwdzBi-BTrXRSywoYuVII

# GET https://localhost:5001/carts HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YmE3ZmFiOS1jZGI3LTQ3OWUtYWIyMS0yNzBkMDhiODhiYjQiLCJpYXQiOiIyMC8wMy8yMDIzIDEwLjQzLjEzIiwiZW1haWwiOiJzbWl0aGFrYW1hdGhAbWFpbC5jb20iLCJuYW1lIjoiU21pdGhhIiwiZXhwIjoxNjc5MzA1MzkzLCJpc3MiOiJTbWl0aGEiLCJhdWQiOiJBZG1pbiJ9.pIJS5xDW_KVOSHJJRp6UNQmi6Eb_Ju3a_WaamsSc5RI

# DELETE https://localhost:5001/carts HTTP/1.1


################################################################################


# Get all Images
# GET https://localhost:5001/images HTTP/1.1

# Get a single category
# GET https://localhost:5001/categorys/1 HTTP/1.1

#Create a Image
POST https://localhost:5001/images HTTP/1.1
content-type: application/json

{
    "ImageURL": "https://source.unsplash.com/164_6wVEHfI"
}

#Assign images to product
POST https://localhost:5001/images/2/assign HTTP/1.1
content-type: application/json

{
    "images": [1,2]
}

# Update a category
# PUT https://localhost:5001/categorys/1 HTTP/1.1
# content-type: application/json

# {
#     "Name": "New Category Updated",
#     "Image": "https://source.unsplash.com/164_6wVEHfI"
# }

# Delete a category
# DELETE https://localhost:5001/images/1 HTTP/1.1

# Get all products by category
# GET https://localhost:5001/categorys/3/products HTTP/1.1
