# GET https://localhost:5001/weatherforecasts HTTP/1.1

# GET https://localhost:5001/categorys HTTP/1.1

# POST https://localhost:5001/categorys HTTP/1.1
# content-type: application/json

# {
#     "Name": "New Category",
#     "Image": "https://source.unsplash.com/164_6wVEHfI"
# }

# PUT https://localhost:5001/categorys/1 HTTP/1.1
# content-type: application/json

# {
#     "Name": "New Category Updated",
#     "Image": "https://source.unsplash.com/164_6wVEHfI"
# }

# DELETE https://localhost:5001/categorys/1 HTTP/1.1


#GET https://localhost:5001/products

# {
#   "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlN2U2YTdhMi1lODcxLTRkZTMtOTM1Yy1hNjM5Njg0ZWNkZDEiLCJpYXQiOiIxNC8wMy8yMDIzIDkuMjMuMDMiLCJlbWFpbCI6InNtaXRoYWthbWF0aEBtYWlsLmNvbSIsIm5hbWUiOiJzbWl0aGEiLCJleHAiOjE2Nzg3ODIxODMsImlzcyI6IlNtaXRoYSIsImF1ZCI6IkFkbWluIn0.c1fusYLAzuJJNaA1HtYmOeAVDlo1Q5Y5a71CtTYlyAw"
# }

#  GET https://localhost:5001/products HTTP/1.1

# GET https://localhost:5001/products
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOTVjOGNhZC1kNWM4LTRjZjItYjA1OS1hYmViZTU4M2FiNzUiLCJpYXQiOiIxNS8wMy8yMDIzIDEyLjE3LjEyIiwiZW1haWwiOiJzbWl0aGFrYW1hdGhAbWFpbC5jb20iLCJuYW1lIjoic21pdGhhIiwiZXhwIjoxNjc4ODc5MDMyLCJpc3MiOiJTbWl0aGEiLCJhdWQiOiJBZG1pbiJ9.FduyrxvLVfu4Sh_C9lufgcYERc36G1_xcie52CGE7eM

# GET https://localhost:5001/products HTTP/1.1

GET https://localhost:5001/categorys/1/products HTTP/1.1

# POST https://localhost:5001/products HTTP/1.1
# content-type: application/json

# {
#     "Title": "New Category Products",
#     "Price": 200,
#     "Description": "New product",
#     "Images": ["https://source.unsplash.com/164_6wVEHfI"],
#     "CategoryID":1
# }

# PUT https://localhost:5001/products/1 HTTP/1.1
# content-type: application/json

# {
#     "Title": "New Product1123",
#     "Price": 500,
#     "Description": "New product",
#     "Images": ["https://source.unsplash.com/164_6wVEHfI"],
#     "CategoryID":1
# }

#  DELETE https://localhost:5001/products/2 HTTP/1.1

# POST https://localhost:5001/signup HTTP/1.1
# content-type: application/json

# {
#     "FirstName": "Nihan",
#     "LastName": "Anwer",
#     "UserName": "nihananwer",
#     "Email": "nihananwer@mail.com",
#     "Password": "Nihan@123",
#     "ConfirmPassword":"Nihan@123"
# }

# POST https://localhost:5001/signup HTTP/1.1
# content-type: application/json

# {
#     "FirstName": "Smitha",
#     "LastName": "Kamath",
#     "UserName": "smithakamath",
#     "Email": "smithakamath@mail.com",
#     "Password": "Smitha@123",
#     "ConfirmPassword":"Smitha@123"
# }

# POST https://localhost:5001/signin HTTP/1.1
# content-type: application/json

# {
#     "Email": "smithakamath@mail.com",
#     "Password": "Smitha@123"
# }

# POST https://localhost:5001/carts HTTP/1.1
# content-type: application/json

# {
#     "UserId":"1f01ae34-d175-4d0a-9584-34f23d06eb11"
# }

# POST https://localhost:5001/carts HTTP/1.1
# content-type: application/json

# {
#     "UserId": "fa41e651-4198-4630-97a5-58952ee320f0",
#     "ProductId": 1,
#     "Quantity":5
# }


//Get all the cart items belonginng to a user
# GET https://localhost:5001/carts/2 HTTP/1.1